files: "^src/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: detect-aws-credentials
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
      - id: debug-statements
        stages: [commit]
      - id: check-added-large-files
        stages: [commit]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        stages: [push]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        stages: [push]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        stages: [push]
