name: Poetry setup
description: Python environment setup with poetry

inputs:
  prefix:
    description: "Prefix for cache keys"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - uses: snok/install-poetry@master

    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash

    - uses: actions/cache@v1
      with:
        path: |
          ~/.cache
          ~/.local/cache
        key: ${{ inputs.prefix }}-cache-${{ runner.os }}-${{ hashFiles('.github/workflows/python/*') }}-${{ steps.get-date.outputs.date }}

    - uses: actions/cache@v1
      id: poetry-lock
      with:
        path: .venv
        key: ${{ inputs.prefix }}-venv-${{ runner.os }}-${{ hashFiles('.github/workflows/python/*') }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.poetry-lock.outputs.cache-hit != 'true'
      shell: bash
      run: |
        poetry install --no-interaction
