name: uv setup
description: Python environment setup with uv

inputs:
  prefix:
    description: "Prefix for cache keys"
    required: false
    default: "uv"

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v2
      with:
        python-version: "3.11"

    - uses: actions/cache@v4
      id: uv-cache
      with:
        path: |
          .venv
          $HOME/.cache/uv
        key: ${{ inputs.prefix }}-uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}

    - name: Sync dependencies
      shell: bash
      run: |
        uv sync --frozen
