name: Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/python
        with:
          prefix: "python"

      - name: isort
        run: poetry run isort --diff --check src/

      - name: black
        run: poetry run black --diff --check src/

      - name: flake8
        run: "poetry run flake8 src/ ||:"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/python
        with:
          prefix: "python"

      - name: build
        run: |
          set -eux
          make build

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: out/

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - run: npm install netlify-cli -g

      - run: netlify deploy --prod --dir=out
