name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Any message. This will be added as a comment in the index.html"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/python
        with:
          prefix: "main"

      - name: build
        run: |
          set -eux
          make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: mariocesar.xyz
